services:
  api:
    container_name: ezauth-api
    build: "./src"
    ports:
      - "3250:80"
    environment:
      - DATABASE_URL=mongodb://admin:admin@db/ezauth?authSource=admin&retryWrites=true&w=majority
      - REDIS_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    volumes:
      - ./config:/src/app/config
      - ./src:/src/app
      - ./uploads:/uploads
      - ./extensions:/src/app/extensions
    command: |
      bash -c 'uvicorn api.main:app --reload --log-level debug --host 0.0.0.0 --port 80'
    depends_on:
      - db
      - redis
  db:
      image: mongo
      ports:
        - '27017:27017'
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=ezauth
      volumes:
        - ezauth-data:/data/db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass admin

volumes:
  ezauth-data: