site_name: EZAuth
site_description: EZAuth is a high performance self-hosted and fully customizable authentication service
use_directory_urls: True
repo_url: https://github.com/JohnGrubba/ezauth
nav:
  - Home: index.md
  - Information: information.md
  - Getting Started:
    - Installation / Setup: getting-started/setup.md
  - Configuration:
    - Configuration File: configuration/configuration.md
    - E-Mail Templates: configuration/email_templates.md
  - Internal API: internal.md
  - Advanced:
    - Advanced E-Mail Templating: advanced/email_templates.md
    - Further Customization: advanced/further_custom.md
    - OAuth: advanced/oauth.md
    - SSL / HTTPS: advanced/ssl.md
theme:
  name: material
  logo: "ezauth_logo.png"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde