services:
  api:
    image: jjtv/ezauth
    ports:
      - "3251:80"
    environment:
      - DATABASE_URL=mongodb://admin:admin@db/ezauth?authSource=admin&retryWrites=true&w=majority
      - REDIS_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    volumes:
      - ./config:/src/app/config
    depends_on:
      - db
      - redis
  db:
      image: mongo
      expose:
        - 27017
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=ezauth
      volumes:
        - ezauth-data:/data/db
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    command: redis-server --requirepass admin

volumes:
  ezauth-data: